steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gke-nginx:${_TAG}", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gke-nginx:${_TAG}"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - 'run'
  - '--namespace=$_NAMESPACE'
  - '--cluster=$_CLUSTER'
  - '--location=$_LOCATION'
  - '--project=$PROJECT_ID'
  - '--filename=$_K8S_YAML_PATH'
  - 'IMAGE_NAME=gcr.io/$PROJECT_ID/gke-nginx:${_TAG}"
substitutions:
  _CLUSTER: fancy-cluster
  _LOCATION: us-central1-f
  _NAMESPACE: default
  _PROJECT_ID: cloudbuild-gke
  _TAG: latest 
  _K8S_YAML_PATH: kubeconfig.yaml
