steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$APP_NAME:${_TAG}", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/$APP_NAME:${_TAG}"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - 'apply'
  - '--namespace=$_NAMESPACE'
  - '--cluster=$_CLUSTER'
  - '--location=$_LOCATION'
  - '--project=$PROJECT_ID'
  - '--filename=$_K8S_YAML_PATH'
  - '--app-name=$_APP_NAME'
  - '-- tag=$_TAG'
substitutions:
  _CLUSTER: fancy-cluster
  _LOCATION: us-central1-f
  _NAMESPACE: default
  _PROJECT_ID: cloudbuild-gke
  _TAG: latest 
  _K8S_YAML_PATH: kubeconfig.yaml
  _APP_NAME: nginx
