apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: <app-name>
  name: <app-name>
spec:
  replicas: 2
  selector:
    matchLabels:
      run: <app-name>
  template:
    metadata:
      labels:
        run: <app-name>
    spec:
      containers:
      - image: gcr.io/<project>/<app-name>:<tag>
        name: <app-name>
        ports:
        - containerPort: 80
---
ind: Service
apiVersion: v1
metadata:
  name: <app-name>
spec:
  selector:
     run: <app-name>
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

